name: Publish to gh-pages


on:
  repository_dispatch:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false